### ISSUE TITLE
Pass options `--enable-repo chef-stable` to `chef_ingredient` resource

### ISSUE THREAD

**Issue by afiune** [chef-cookbooks/chef-ingredient#38] opened 2015-09-09 15:30 UTC
As a user I expect to be able to have multiple `chef_ingredient` resources in the same recipe without failing because the `chef-stable` repo is disabled, otherwise I need to re-run multiple times or modify the repo manually to enable it.

**Problem Description**

With PR https://github.com/chef/chef-server/pull/500 when you run `reconfigure` it automatically disable the `chef-stable` repo. Then the next time we try to install a ingredient it fails.

**Proposal Solution**

Pass options `--enable-repo chef-stable` to `chef_ingredient` resource by default.

**Comment by lamont-granquist** [comment] 2015-09-09 20:46
yeah, i can see people wanting to have chef-client be current but chef-server be stable and with only one packagecloud repo for stable and current there's no way to specify that now.  the chef_ingredient provider should probably enable and disable the correct repos every time.

**Comment by afiune** [comment] 2015-09-09 21:16
@lamont-granquist `current`? I'm sorry but I might be missing something here.. We are talking about the `stable` repo.. :smile:

**Comment by lamont-granquist** [comment] 2015-09-09 21:57
It really needs to assert all of its state is correct and if it needs current to enable current and if it needs stable to enable stable.

**Comment by afiune** [comment] 2015-09-09 22:03
Fair enough..

**Comment by sersut** [comment] 2015-09-10 15:19
I agree with @lamont-granquist that we need to have a per ingredient configuration of `:current` or `:stable`. 

But I do not quite follow how `--enable-repo chef-stable` will help. Looks like chef/chef-server#500 intentionally disables the repo to protect against unintended upgrades. If we add `--enable-repo chef-stable` to the `install` or `upgrade` action we might cause an unintended upgrade if the `version` is floating for `chef_ingredient` no?

**Comment by lamont-granquist** [comment] 2015-09-10 17:02
because the repo is shared across projects, including the client and the server, i'm fairly confident that chef/chef-server#500 is absolutely the wrong solution to this problem -- since its a shared resource the chef-server doesn't 'own' it and can't make that 'call' and needs to stop doing that.

we should have the default `:install` action here be 'safe' and not do any upgrades (even if you float the version to `:latest` an `:install` action should not do an 'upgrade' to the latest version).  if someone does `:upgrade` and doesn't pin any kind of version then we should default to non-major-version upgrades -- people should not be doing that outside of CI testing though (where it might be very useful).

**Comment by lamont-granquist** [comment] 2015-09-10 17:05
And in the client world, doing an `:upgrade` and letting version float to the latest minor version is the common case of doing upgrades.  We need to not make that overly hard or impossible to do.  Trying to make it impossible to do that for the server conflicts with the goal of keeping the client up-to-date.

**Comment by sersut** [comment] 2015-09-10 20:28
In violent agreement that `:install` should not upgrade if there is an installed and `:upgrade` by default should only upgrade inside the same major version number. 

@afiune not sure what to do to work around chef/chef-server#500 but i don't think adding `enable-repos` to chef-ingredient is the right solution.

**Comment by lamont-granquist** [comment] 2015-09-14 21:23
So most likely `chef_ingredient` needs to support passing arbitrary flags to the underlying package resource to enable repos, disable repos, or do whatever else is necessary.

By default it should do nothing.  The common and best case to support is when the package repo is setup correctly and does not need to be enabled/disabled, and the chef_ingredient recipe is responsible for upgrades/installs.

Where this is a problem is when people have autoupdates running and the repo is enabled so the chef-server gets autoupdated.  Which, for one thing is a horrible production practice.  But aside from that, it should be the responsibility of the auto-updating user to set up their own policy explicitly.  So at that point they're responsible for installing the package cloud repo and making it disabled, and responsible for passing in the flag to enable it as appropriate to the right chef_ingredient behavior.

Then the problem is just one of documentation as to how to make the use case work.

I'm very :-1: on passing these flags into the package resource by default.

And probably https://github.com/chef/chef-server/pull/500 needs to be rethought a bit in terms of separation of responsibilities.  It looks to me more appropriate to rip most of that code out and make chef_ingredient responsible for it and stop having the chef-server manage its own repo.  Like there just shouldn't be any apt_repository or yum_repository commands in there and it shouldn't be attempting to manage its own install sources.  Since there's one repo for client and server, the server doesn't own that and shouldn't be setting it up, needs to go into a separate cookbook that uses chef_ingredient and is either the chef-server community cookbook or is rolled by the user.

**Comment by sersut** [comment] 2015-12-09 19:52
Given the above conversations I am closing this @afiune. Let's re-open and discuss if necessary.

**Closed by sersut** 2015-12-09 19:52 UTC
