### ISSUE TITLE
Undefined Method 'property'

### ISSUE THREAD

**Issue by anupamkakade** [chef-cookbooks/chef-ingredient#98] opened 2016-04-14 04:19 UTC
Hi ,
I am getting error 
```
undefined method `property' for Chef::Resource::ChefIngredientIngredientConfig:Class
```

The full stack trace is here 

```
==> chef-server: ================================================================================
==> chef-server: Recipe Compile Error in /var/chef/cache/cookbooks/chef-ingredient/resources/ingredient_config.rb
==> chef-server: ================================================================================
==> chef-server: NoMethodError
==> chef-server: -------------
==> chef-server: undefined method `property' for Chef::Resource::ChefIngredientIngredientConfig:Class
==> chef-server: Cookbook Trace:
==> chef-server: ---------------
==> chef-server:   /var/chef/cache/cookbooks/chef-ingredient/resources/ingredient_config.rb:26:in `class_from_file'
==> chef-server: Relevant File Content:
==> chef-server: ----------------------
==> chef-server: /var/chef/cache/cookbooks/chef-ingredient/resources/ingredient_config.rb:
==> chef-server:  19:  include ChefIngredientCookbook::Helpers
==> chef-server:  20:  
==> chef-server:  21:  resource_name :ingredient_config
==> chef-server:  22:  
==> chef-server:  23:  actions :render, :add
==> chef-server:  24:  default_action :render
==> chef-server:  25:  
==> chef-server:  26>> property :product_name, String, name_property: true
==> chef-server:  27:  property :sensitive, [TrueClass, FalseClass], default: false
==> chef-server:  28:  property :config, String, default: nil
==> chef-server:  29:  
==> chef-server:  30:  action :render do
==> chef-server:  31:    target_config = ingredient_config_file
==> chef-server:  32:    return if target_config.nil?
==> chef-server:  33:  
==> chef-server:  34:    directory ::File.dirname(target_config) do
==> chef-server:  35:      recursive true
==> chef-server: Running handlers:
```

Does any one know how to fix this ? 

(edited to make stacktrace and error more readable)

**Comment by sersut** [comment] 2016-04-14 17:52
`property` is a new DSL method introduced with Chef Client 12.5.0. [This](https://github.com/chef-cookbooks/chef-ingredient/commit/4a0759b03823a0e286211aef855ecf08e947c593#diff-b4b720ad861e54548d596fa3ca1ebc84) commit changed chef-ingredient to make use of them. 

I am guessing that your version is < 12.5.0. An upgrade should fix this issue.

**Comment by tas50** [comment] 2016-07-29 22:58
Closing since this is caused by not running Chef 12

**Closed** 2016-07-29 22:57 UTC
